sudo: required
services:
    - docker

before_install:
    - docker build -t dasrajendra2004/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dasrajendra2004/docker-react npm run test